version: "3"
services:
  backend:
    build: backend
    ports:
      - 8080:8080
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/user:/usr/src/app/user
      - ./nginx/content:/usr/src/app/content
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/forum.crt:/etc/ssl/forum.crt
      - ./nginx/forum.key:/etc/ssl/forum.key
  frontend:
    build: frontend
    ports:
      - 3000:3000
